---
title: C6310
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6310
helpviewer_keywords:
- C6310
ms.assetid: e759eb63-883f-4c3e-bf2f-b924ff511405
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 3b7d3c82ed40f270c9bbe83ba0a0408d50dddcc1
ms.sourcegitcommit: 240c8b34e80952d00e90c52dcb1a077b9aff47f6
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/23/2018
ms.locfileid: "49837378"
---
# <a name="c6310"></a>C6310
Advertencia C6310: una constante no válida en el filtro de excepción puede provocar un comportamiento inesperado

Este mensaje indica que se ha detectado una constante no válida en la expresión de filtro de controlador de excepciones estructurado. Las constantes definidas para su uso en la expresión de filtro de controlador de excepciones estructurado son:

- `EXCEPTION_CONTINUE_EXECUTION`

- `EXCEPTION_CONTINUE_SEARCH`

- `EXCEPTION_EXECUTE_HANDLER`

Estos valores se definen en el excpt.h de archivo de encabezado en tiempo de ejecución.

Uso de una constante que no está en la lista anterior puede provocar un comportamiento inesperado.

## <a name="example"></a>Ejemplo

El código siguiente genera esta advertencia:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (EXCEPTION_ACCESS_VIOLATION)
  {
    puts("Exception Occurred");
  }
}
```

Para corregir esta advertencia, utilice el código siguiente:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Exception Occurred");
  }
}
```